name: RSS to Slack

on:
  schedule:
    - cron: '0 */12 * * *'  # 매 5분마다 실행
  workflow_dispatch:

jobs:
  rss_to_slack:
    runs-on: ubuntu-latest

    steps:
      # 최신 버전의 actions 사용
      - name: Check out the repository
        uses: actions/checkout@v3  # @v2에서 @v3으로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v4  # @v2에서 @v4으로 업데이트
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser slack_sdk openai==0.28.0  # 특정 버전 설치 후 호환성 확인
          python -m pip show openai  # 설치된 openai 라이브러리 버전 확인

      - name: Run the RSS to Slack script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python rss_to_slack.py

      # - name: Run the PubMed to Slack script
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: |
      #     python pubmed_to_slack.py
